"""create monitors

Revision ID: 05ad4f8ac94e
Revises: ed43b0f7ee6d
Create Date: 2026-02-17 23:59:43.833043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ad4f8ac94e'
down_revision: Union[str, Sequence[str], None] = 'ed43b0f7ee6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_url', sa.String(length=1000), nullable=False),
    sa.Column('monitor_type', sa.String(length=50), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitors_id'), 'monitors', ['id'], unique=False)
    op.create_index(op.f('ix_monitors_user_id'), 'monitors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitors_user_id'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_id'), table_name='monitors')
    op.drop_table('monitors')
    # ### end Alembic commands ###
